---
source: "./.github/agents/UIDesigner.agent.md"
chunk_index: 2
token_estimate: 3780
hash: "pending-generation"
summary: "Component specification templates, design token schema, user flow diagrams, design system integration, handoff protoc..."
---

## 9. Component Specification Templates

### Component Spec Entry Format

Every component in `component-specs.md` follows this structure:

```markdown
### ComponentName

**Description:** [What it does, when it's used]

#### Props

| Prop | Type | Required | Default | Description |
|------|------|----------|---------|-------------|
| `title` | `string` | yes | — | Primary display text |
| `variant` | `'compact' \| 'detailed'` | no | `'compact'` | Visual style variant |
| `onAction` | `() => void` | no | — | Callback on primary action |
| `isLoading` | `boolean` | no | `false` | Shows skeleton state |
| `status` | `'active' \| 'archived' \| 'draft'` | yes | — | Item lifecycle status |

#### States

| State | Description | Visual Indicators |
|-------|-------------|-------------------|
| Default | Resting state | Standard colors, no highlight |
| Hover | Mouse over component | Subtle elevation or background shift |
| Selected | Active/focused item | Primary color border, filled checkbox |
| Loading | Data being fetched | Skeleton placeholder, pulsing animation |
| Error | Failed to load/save | Error border color, error message slot |
| Empty | No content present | Placeholder text and illustration |
| Disabled | Non-interactive | Reduced opacity, no pointer events |

#### Variants

| Variant | Use Case | Key Differences |
|---------|----------|-----------------|
| `compact` | List views, dense layouts | Single-line, minimal info |
| `detailed` | Focus views, dashboards | Multi-line, full metadata |

#### Accessibility

| Aspect | Requirement |
|--------|-------------|
| ARIA Role | `role="listitem"` or appropriate semantic role |
| Keyboard Nav | Tab to focus, Enter/Space to select, Escape to deselect |
| Screen Reader | Announces: "[title], [status], [variant]" |
| Focus Indicator | Visible focus ring (2px solid, primary color) |
| Color Independence | Status conveyed by icon + text, not color alone |

#### Responsive Behavior

| Breakpoint | Behavior |
|------------|----------|
| Mobile (< 640px) | Full width, stacked layout, touch targets ≥ 44px |
| Tablet (640–1024px) | Two-column grid, medium spacing |
| Desktop (> 1024px) | Multi-column, hover states active, compact spacing |
```

### Spec Completeness Rules

```
1. EVERY component must have at least: default, hover, loading, error states
2. EVERY prop must have a TypeScript type — no `any`, no untyped
3. EVERY interactive component must define keyboard navigation
4. EVERY component must specify behavior at all 3 breakpoints
5. Props marked required MUST NOT have defaults (and vice versa)
6. Callback props describe WHEN they fire and WHAT they pass
```

## 10. Design Token Schema

Design tokens go in `design-tokens.json`. Follow this JSON structure:

```json
{
  "$schema": "design-tokens-v1",
  "metadata": {
    "project": "project-name",
    "generated_by": "UIDesigner",
    "date": "YYYY-MM-DD",
    "stitch_project_id": "stitch-xxx"
  },
  "colors": {
    "primary": { "value": "#2563EB", "usage": "Primary actions, links" },
    "primaryHover": { "value": "#1D4ED8", "usage": "Primary hover state" },
    "secondary": { "value": "#64748B", "usage": "Secondary text, borders" },
    "success": { "value": "#16A34A", "usage": "Success states, confirmations" },
    "warning": { "value": "#D97706", "usage": "Warnings, caution states" },
    "error": { "value": "#DC2626", "usage": "Errors, destructive actions" },
    "background": { "value": "#FFFFFF", "usage": "Page background" },
    "surface": { "value": "#F8FAFC", "usage": "Card/panel backgrounds" },
    "text": { "value": "#0F172A", "usage": "Primary text" },
    "textMuted": { "value": "#64748B", "usage": "Secondary/helper text" }
  },
  "typography": {
    "fontFamily": {
      "sans": { "value": "Inter, system-ui, sans-serif", "usage": "Body text" },
      "mono": { "value": "JetBrains Mono, monospace", "usage": "Code blocks" }
    },
    "fontSize": {
      "xs": { "value": "0.75rem", "usage": "Captions, badges" },
      "sm": { "value": "0.875rem", "usage": "Helper text, metadata" },
      "base": { "value": "1rem", "usage": "Body text" },
      "lg": { "value": "1.125rem", "usage": "Subheadings" },
      "xl": { "value": "1.25rem", "usage": "Section headings" },
      "2xl": { "value": "1.5rem", "usage": "Page headings" },
      "3xl": { "value": "1.875rem", "usage": "Hero text" }
    },
    "fontWeight": {
      "normal": { "value": "400" },
      "medium": { "value": "500" },
      "semibold": { "value": "600" },
      "bold": { "value": "700" }
    },
    "lineHeight": {
      "tight": { "value": "1.25" },
      "normal": { "value": "1.5" },
      "relaxed": { "value": "1.75" }
    }
  },
  "spacing": {
    "xs": { "value": "0.25rem", "px": "4px" },
    "sm": { "value": "0.5rem", "px": "8px" },
    "md": { "value": "1rem", "px": "16px" },
    "lg": { "value": "1.5rem", "px": "24px" },
    "xl": { "value": "2rem", "px": "32px" },
    "2xl": { "value": "3rem", "px": "48px" }
  },
  "breakpoints": {
    "mobile": { "value": "640px", "query": "(max-width: 639px)" },
    "tablet": { "value": "1024px", "query": "(min-width: 640px) and (max-width: 1023px)" },
    "desktop": { "value": "1024px", "query": "(min-width: 1024px)" }
  },
  "borderRadius": {
    "sm": { "value": "0.25rem" },
    "md": { "value": "0.375rem" },
    "lg": { "value": "0.5rem" },
    "full": { "value": "9999px" }
  },
  "shadows": {
    "sm": { "value": "0 1px 2px rgba(0,0,0,0.05)" },
    "md": { "value": "0 4px 6px rgba(0,0,0,0.07)" },
    "lg": { "value": "0 10px 15px rgba(0,0,0,0.1)" }
  }
}
```

**Token rules:**
- Every color must have a `usage` description
- Semantic names only — no `blue500`, use `primary`
- Tokens are the contract: Frontend must use these values, not ad-hoc values
- If a project has existing tokens, extend rather than replace

## 11. User Flow Diagrams

Document key user journeys as Mermaid flowcharts in `user-flows.md`:

```markdown
## Flow: [Flow Name]

**Trigger:** [What initiates this flow]
**Actor:** [User role]
**Happy path outcome:** [Expected result]

\`\`\`mermaid
flowchart TD
    A[User lands on Dashboard] --> B{Has tasks?}
    B -->|Yes| C[Display task list]
    B -->|No| D[Show empty state with CTA]
    D --> E[User clicks 'Create Task']
    C --> E
    E --> F[Task creation modal opens]
    F --> G[User fills form]
    G --> H{Valid?}
    H -->|Yes| I[Save task, show success toast]
    H -->|No| J[Show inline validation errors]
    J --> G
    I --> C
\`\`\`
```

**Flow coverage requirements:**
- Every screen in the inventory must appear in at least one flow
- Cover the happy path AND at least one error/edge path per flow
- Include decision points (diamonds) for conditional behavior
- Label all transitions

## 12. Design System Integration

When an existing design system or token set is present:

1. **Read existing tokens** — check `design-tokens.json` or equivalent
2. **Align new tokens** — extend existing palette, don't conflict
3. **Reuse components** — reference existing component specs before creating new
4. **Document deviations** — if a new pattern diverges, state why in specs
5. **Propose updates** — if existing tokens need expansion, note in specs

When no design system exists:
- Create the token set from scratch (§10 schema)
- Design for consistency across all screens in the project
- Document design rationale in `component-specs.md` header

## 13. Handoff Protocol — UIDesigner → Frontend Engineer

The Frontend Engineer reads UIDesigner output as upstream artifacts. Ensure:

| Requirement | How to Satisfy |
|-------------|---------------|
| Buildable specs | Every component has typed props, defined states, and responsive rules |
| Visual reference | Screenshots in `screenshots/` at all breakpoints |
| Token contract | `design-tokens.json` is the single source of truth for all style values |
| Flow context | `user-flows.md` shows how components compose into journeys |
| Route mapping | `screen-inventory.md` maps screens to routes |
| No ambiguity | If something is unclear, add a note rather than leaving it implicit |

**Handoff checklist (run before marking task complete):**
- [ ] Every screen has a route in `screen-inventory.md`
- [ ] Every component has a spec in `component-specs.md`
- [ ] Every component has ≥ 4 states defined
- [ ] Every component has TypeScript-typed props
- [ ] Every component has responsive behavior for 3 breakpoints
- [ ] Design tokens cover all colors, fonts, and spacing used
- [ ] At least one screenshot per screen exists
- [ ] User flows cover all screens and key interactions

## 14. Quality Checklist

Self-assess before completing. Score each dimension 1–10:

```
PRD Coverage:       ?/10  — Do designs address all user stories?
Component Coverage: ?/10  — Are all UI elements specified?
State Coverage:     ?/10  — Are all states (load, error, empty) defined?
A11y Coverage:      ?/10  — ARIA roles, keyboard nav, screen reader?
Responsive:         ?/10  — Mobile, tablet, desktop for every screen?
Token Consistency:  ?/10  — All values from design-tokens.json?
Flow Completeness:  ?/10  — Happy + error paths in user flows?
Handoff Readiness:  ?/10  — Can Frontend build from specs alone?

TOTAL: ?/80  (minimum 56/80 to pass — 70% threshold)
```

If total < 56, iterate before submitting. Identify the lowest-scoring
dimension and address it first.

## 15. Tool Permissions

### Allowed Tools

| Tool | Purpose | Constraint |
|------|---------|-----------|
| `search/codebase` | Find existing components/tokens | Read-only |
| `search/textSearch` | Search existing design docs | Read-only |
| `search/fileSearch` | Locate design files | Read-only |
| `search/listDirectory` | Explore project structure | Read-only |
| `read/readFile` | Read PRD, architecture, tokens | Read-only |
| `read/problems` | Check for file issues | Read-only |
| `edit/createFile` | Create design spec files | `docs/design-specs/` only |
| `edit/editFile` | Update design spec files | `docs/design-specs/` only |
| `stitch/*` | All Stitch MCP tools | Design generation |
| `playwright/browser_navigate` | Open Stitch previews | Visual validation |
| `playwright/browser_snapshot` | Capture a11y tree | Structure verification |
| `playwright/browser_take_screenshot` | Visual capture | Save to screenshots/ |
| `memory/create_entities` | Persist design decisions | Knowledge persistence |
| `memory/search_nodes` | Recall past design context | Knowledge retrieval |
| `memory/add_observations` | Record design observations | Knowledge persistence |
